In [1]:
import pandas as pd
import geopandas as gpd

In [78]:
trash_data = gpd.read_file('./trash_hauler_report.csv')
trash_data

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y
0,25270,11/01/17,Trash - Backdoor,"house with the wheel chair ramp, they share dr...",3817 Crouch Dr,37207,RED RIVER,3205,2,1727970.41206786,686779.478088711
1,25274,11/01/17,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,4028 Clarksville Pike,37218,RED RIVER,4202,1,1721259.36568104,685444.799565154
2,25276,11/01/17,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,6528 Thunderbird Dr,37209,RED RIVER,4205,20,1707026.75348931,659887.471571312
3,25307,11/01/17,Trash - Curbside/Alley Missed Pickup,missed,2603 old matthews rd,37207,WASTE IND,2206,2,1735691.77097349,685027.245922773
4,25312,11/01/17,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,604 croley dr,37209,RED RIVER,4203,20,1710185.77229504,664205.101065545
...,...,...,...,...,...,...,...,...,...,...,...
20221,267125,11/01/19,Trash - Curbside/Alley Missed Pickup,MISSED...NEIGHBORS MISSED,2731 Murfreesboro Pike,37013,RED RIVER,4502,32,1781137.26293528,632448.551143857
20222,267126,11/01/19,Trash - Curbside/Alley Missed Pickup,entire alley,"1621 Long Ave, Nashville, TN 37206, United States",37206,METRO,9508,6,1749711.39882271,669201.601569129
20223,267130,11/01/19,Trash - Curbside/Alley Missed Pickup,missed several,"2943 Windemere Cir, Nashville, TN 37214, Unite...",37214,RED RIVER,1502,15,1770293.38813099,674936.303809043
20224,267134,11/01/19,Trash - Curbside/Alley Missed Pickup,Caller stated trash was missed & were only pic...,"3325 Murfreesboro Pike, Nashville, TN 37013, U...",37013,RED RIVER,4502,32,1785224.99799806,627146.400187231
20225,267137,11/01/19,Trash - Curbside/Alley Missed Pickup,possibly others missed as well,"604 Somerset Ct, Nashville, TN 37217, United S...",37217,RED RIVER,2505,29,1781360.32310215,637742.006845765

In [17]:
# Finding unique values for the Request column 
pd.unique(trash_data['Request'])

array(['Trash - Backdoor', 'Trash - Curbside/Alley Missed Pickup',
       'Trash Collection Complaint', 'Damage to Property'], dtype=object)

In [35]:
backdoor = trash_data.loc[trash_data['Request'] == 'Trash - Backdoor']
backdoor.shape

(2629, 11)

In [36]:
cs_alley = trash_data.loc[trash_data['Request'] == 'Trash - Curbside/Alley Missed Pickup']
cs_alley.shape

(15028, 11)

In [15]:
complaint = trash_data.loc[trash_data['Request'] == 'Trash Collection Complaint']
#complaint

In [39]:
contains_miss = complaint['Description'].str.contains('miss', case = 'False', na ='False')
#contains_miss

C:\Users\EpicWork\AppData\Local\Temp\ipykernel_13892\3712832755.py:1: FutureWarning: Allowing a non-bool 'na' in obj.str.contains is deprecated and will raise in a future version.
  contains_miss = complaint['Description'].str.contains('miss', case = 'False', na ='False')

In [40]:
miss_complaint = complaint[contains_miss]
miss_complaint.shape

(453, 11)

In [43]:
miss_all = pd.concat([backdoor, cs_alley, miss_complaint], ignore_index = 'True')

In [83]:
miss_all['Short Address'] = miss_all['Incident Address'].str.split(',', n=1).str[0]
miss_all['Short Address'] = miss_all['Short Address'].str.lower()
miss_all

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y,Short Address
0,25270,11/01/17,Trash - Backdoor,"house with the wheel chair ramp, they share dr...",3817 Crouch Dr,37207,RED RIVER,3205,2,1727970.41206786,686779.478088711,3817 crouch dr
1,25692,11/02/17,Trash - Backdoor,Backdoor/miss for last Friday. Does not unders...,3041 Fieldstone Dr,37013,RED RIVER,3504,29,1785677.15882833,633139.246264943,3041 fieldstone dr
2,25775,11/02/17,Trash - Backdoor,Missed trash pickup said has been picking up b...,4625 long br,37013,RED RIVER,4505,28,1770350.41605229,634143.871818357,4625 long br
3,25802,11/02/17,Trash - Backdoor,Missed.,4828 Cimarron Way,37013,RED RIVER,3404,30,1766186.56409375,629785.602877192,4828 cimarron way
4,25858,11/03/17,Trash - Backdoor,Missed- she said her grandson was over yesterd...,2005 Lebanon Pike,37210,RED RIVER,1504,15,1760561.7630735,665276.001224629,2005 lebanon pike
...,...,...,...,...,...,...,...,...,...,...,...,...
18105,266466,10/31/19,Trash Collection Complaint,"Paid/Backdoor-Trash missed last Thursday, does...","809 Winthorne Ct, Nashville, TN 37217, United ...",37217,RED RIVER,1402,16,1759043.58424902,651549.019214337,809 winthorne ct
18106,266628,10/31/19,Trash Collection Complaint,Disabled caller stated she is keep getting mis...,"1719 Windover Dr, Nashville, TN 37218, United ...",37218,RED RIVER,4202,2,1718308.69339541,680762.907491275,1719 windover dr
18107,266708,11/01/19,Trash Collection Complaint,Caller stated her trash has been missed for 2 ...,"4305 Granny White Pike, Nashville, TN 37204, U...",37204,RED RIVER,3302,25,1731857.80036635,644223.201524295,4305 granny white pike
18108,266710,11/01/19,Trash Collection Complaint,"Trash/has been missed for weeks in a row, curb...","3325 Murfreesboro Pike, Nashville, TN 37013, U...",37013,RED RIVER,4502,32,1785224.99799806,627146.400187231,3325 murfreesboro pike
18109,266732,11/01/19,Trash Collection Complaint,Caller stated her trash misses her trash all t...,"2114 Vine Hill Rd, Nashville, TN 37204, United...",37204,METRO,9406,17,1741197.38231891,655129.23648106,2114 vine hill rd

In [84]:
miss_count_by_address = miss_all['Short Address'].value_counts().reset_index(name='Missed Pickups')
#miss_count_by_address = miss_count_by_address.to_frame()
miss_count_by_address

                  Short Address  Missed Pickups
0       110 george l davis blvd              27
1        12546 old hickory blvd              21
2      5135 hickory hollow pkwy              20
3               802 crescent rd              19
4                  1584 bell rd              19
...                         ...             ...
11305             739 rodney dr               1
11306           3805 elkins ave               1
11307      800 old hickory blvd               1
11308        631 blackstone ave               1
11309         2114 vine hill rd               1

[11310 rows x 2 columns]

In [85]:
frequently_missed = miss_count_by_address.loc[miss_count_by_address['Missed Pickups'] > 1]
frequently_missed

                 Short Address  Missed Pickups
0      110 george l davis blvd              27
1       12546 old hickory blvd              21
2     5135 hickory hollow pkwy              20
3              802 crescent rd              19
4                 1584 bell rd              19
...                        ...             ...
3362          321 charmaine ct               2
3363           2243 foster ave               2
3364           120 islandia dr               2
3365        89 riverpoint pass               2
3366     115 rosa l parks blvd               2

[3367 rows x 2 columns]

In [86]:
frequently_missed['Fine Amount'] = (frequently_missed['Missed Pickups'] - 1) * 200
frequently_missed

C:\Users\EpicWork\AppData\Local\Temp\ipykernel_13892\825867008.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frequently_missed['Fine Amount'] = (frequently_missed['Missed Pickups'] - 1) * 200

                 Short Address  Missed Pickups  Fine Amount
0      110 george l davis blvd              27         5200
1       12546 old hickory blvd              21         4000
2     5135 hickory hollow pkwy              20         3800
3              802 crescent rd              19         3600
4                 1584 bell rd              19         3600
...                        ...             ...          ...
3362          321 charmaine ct               2          200
3363           2243 foster ave               2          200
3364           120 islandia dr               2          200
3365        89 riverpoint pass               2          200
3366     115 rosa l parks blvd               2          200

[3367 rows x 3 columns]

In [92]:
total_damages = frequently_missed['Fine Amount'].sum()
def currency_format(amount):
    return "${:,}".format(amount)
formatted_cost = currency_format(total_damages)
print(f"The total amount in damages is {formatted_cost}")

The total amount in damages is $1,360,000

<h1>Investigating metro crews vs contractor performance</h1>

<h2>Metro Performance</h2>

In [100]:
metro = miss_all.loc[miss_all['Trash Hauler'].str.lower() == 'metro'].reset_index()
metro

,index,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y,Short Address
0,11,26275,11/06/17,Trash - Backdoor,customer says trash pickup was missed again,936 Cahal Ave,37206,METRO,9507,5,1748206.4428172,679272.537889391,936 cahal ave
1,20,27018,11/08/17,Trash - Backdoor,cust says missed pickup,2833 Georgia Ave B,37209,METRO,9303,21,1726032.30907294,664835.417901276,2833 georgia ave b
2,27,28143,11/15/17,Trash - Backdoor,Missed pickup,302 EDITH AVE,37207,METRO,9206,5,1742657.76456183,681194.400681653,302 edith ave
3,32,28467,11/16/17,Trash - Backdoor,"BACKDOOR/TRASH KEEPS GETTING MISSED, WEDNESDAY...",1421 JONES AVE,37207,METRO,9203,5,1744686.56384716,679822.398822455,1421 jones ave
4,37,28690,11/17/17,Trash - Backdoor,"Extra trash pickup, truck came and left his ca...",1626 Shelby Ave,37206,METRO,9508,6,1749899.66436337,669422.242228153,1626 shelby ave
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3023,18085,254330,10/02/19,Trash Collection Complaint,My trash has not been picked u p in several we...,"2010 Beech Ave, Nashville, TN 37204, United St...",37204,METRO,9401,17,1738012.19918316,656168.000664696,2010 beech ave
3024,18086,255455,10/04/19,Trash Collection Complaint,"This was not an extra trash/pick up, it's was ...","1113 N 6th St, Nashville, TN 37207, United States",37207,METRO,9203,5,1744041.79970384,677230.398806637,1113 n 6th st
3025,18094,261316,10/18/19,Trash Collection Complaint,Curb trash/missed Friday/everyone else was emp...,"1109 Leland Ave, Nashville, TN 37216, United S...",37216,METRO,9507,7,1750973.71788665,681739.941081423,1109 leland ave
3026,18095,261420,10/18/19,Trash Collection Complaint,Entire Alley trash/missed pickup {Thursday} ca...,"917 South St, Nashville, TN 37203, United States",37203,METRO,9407,17,1737818.36597359,660991.302742682,917 south st
3027,18109,266732,11/01/19,Trash Collection Complaint,Caller stated her trash misses her trash all t...,"2114 Vine Hill Rd, Nashville, TN 37204, United...",37204,METRO,9406,17,1741197.38231891,655129.23648106,2114 vine hill rd

In [101]:
metro_miss_count = metro['Short Address'].value_counts().reset_index(name='Missed Pickups')

In [102]:
metro_freq_miss = metro_miss_count.loc[metro_miss_count['Missed Pickups'] > 1]
metro_freq_miss['Fine Amount'] = (metro_freq_miss['Missed Pickups'] - 1) * 200
metro_freq_miss

C:\Users\EpicWork\AppData\Local\Temp\ipykernel_13892\196924443.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metro_freq_miss['Fine Amount'] = (metro_freq_miss['Missed Pickups'] - 1) * 200

               Short Address  Missed Pickups  Fine Amount
0       1816 jo johnston ave              18         3400
1    110 george l davis blvd              17         3200
2          2813 delaware ave              12         2200
3          2801 delaware ave              11         2000
4           2415 brasher ave              10         1800
..                       ...             ...          ...
551         836 cherokee ave               2          200
552             913 west ave               2          200
553          1609 lillian st               2          200
554      1922 ed temple blvd               2          200
555             823 knox ave               2          200

[556 rows x 3 columns]

In [103]:
metro_damages = metro_freq_miss['Fine Amount'].sum()
metro_format = currency_format(metro_damages)
metro_format

'$215,800'

<h2>Red River Performance</h2>

In [98]:
trash_data['Trash Hauler'].unique()

array(['RED RIVER', 'WASTE IND', 'METRO', '', 'Metro'], dtype=object)

In [106]:
red_river = miss_all.loc[miss_all['Trash Hauler'] == 'RED RIVER'].reset_index()
#red_river

In [107]:
red_river_miss_count = red_river['Short Address'].value_counts().reset_index(name='Missed Pickups')

In [108]:
red_river_freq_miss = red_river_miss_count.loc[red_river_miss_count['Missed Pickups'] > 1]
red_river_freq_miss['Fine Amount'] = (red_river_freq_miss['Missed Pickups'] - 1) * 200
red_river_freq_miss

C:\Users\EpicWork\AppData\Local\Temp\ipykernel_13892\2638443975.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  red_river_freq_miss['Fine Amount'] = (red_river_freq_miss['Missed Pickups'] - 1) * 200

                 Short Address  Missed Pickups  Fine Amount
0       12546 old hickory blvd              21         4000
1     5135 hickory hollow pkwy              19         3600
2                 1584 bell rd              18         3400
3              6007 obrien ave              17         3200
4              802 crescent rd              17         3200
...                        ...             ...          ...
2412           468 sunliner dr               2          200
2413            1707 porter rd               2          200
2414                613 may dr               2          200
2415              722 dover rd               2          200
2416   2645 old buena vista rd               2          200

[2417 rows x 3 columns]

In [109]:
red_river_damages = red_river_freq_miss['Fine Amount'].sum()
red_river_format = currency_format(red_river_damages)
red_river_format

'$970,000'

<h2>Waste Ind Performance</h2>

In [111]:
waste_ind = miss_all.loc[miss_all['Trash Hauler'] == 'WASTE IND'].reset_index()
#waste_ind

In [112]:
waste_ind_miss_count = waste_ind['Short Address'].value_counts().reset_index(name='Missed Pickups')

In [113]:
waste_ind_freq_miss = waste_ind_miss_count.loc[waste_ind_miss_count['Missed Pickups'] > 1]
waste_ind_freq_miss['Fine Amount'] = (waste_ind_freq_miss['Missed Pickups'] - 1) * 200
waste_ind_freq_miss

C:\Users\EpicWork\AppData\Local\Temp\ipykernel_13892\2429048491.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  waste_ind_freq_miss['Fine Amount'] = (waste_ind_freq_miss['Missed Pickups'] - 1) * 200

          Short Address  Missed Pickups  Fine Amount
0      15 hermitage ave              16         3000
1        123 37th ave n              10         1800
2    1011 elm hill pike              10         1800
3       3406 batavia st              10         1800
4       1517 12th ave n               7         1200
..                  ...             ...          ...
223       105 evelyn dr               2          200
224          72 lyle ln               2          200
225        34 n hill st               2          200
226      916 32nd ave n               2          200
227      926 32nd ave n               2          200

[228 rows x 3 columns]

In [114]:
waste_ind_damages = waste_ind_freq_miss['Fine Amount'].sum()
waste_ind_format = currency_format(waste_ind_damages)
waste_ind_format

'$78,200'

<h1>Finding total missed pickups by route</h1>

In [120]:
miss_by_route = miss_all['Request Number'].groupby(miss_all['Trash Route']).count().reset_index()
miss_by_route

    Trash Route  Request Number
0                           767
1          1201             175
2          1202              93
3         1202S               4
4          1203              74
..          ...             ...
168        9504              44
169        9505              58
170        9506              67
171        9507              76
172        9508             120

[173 rows x 2 columns]